Exit correctly if next tag can not be determined

diff --git a/tag-kinesis-repo b/tag-kinesis-repo
--- a/tag-kinesis-repo
+++ b/tag-kinesis-repo
@@ -16,6 +16,12 @@ fi
 
 
 tag=$(latest-tag $tagPattern)
+
+if [ $? -ne 0 ]; then
+  echo "Error: $tag"
+  exit 1
+fi
+
 read -p "Push tag $tag (y/n)? " shouldPushTag
 if [ "$shouldPushTag" = "y" ]; then
   git tag $tag
